const movies = [
  {
    "id": 1,
    "title": "The Shawshank Redemption",
    "image": "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hBcY0fE9pfXzvVaY4GKarweriG2.jpg",
    "year": "1994",
    "genre": "Drama",
    "rating": "9.3",
    "description": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    "director": "Frank Darabont",
    "cast": ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    "languages": ["English", "Spanish", "Tamil"],
    "price": {
      "HD (2160p)": 12.99,
      "HD (1080p)": 9.99,
      "SD (720p)": 8.99,
      "SD (480p)": 7.99,
      "SD (240p)": 5.99,
    },
  },
  {
    "id": 2,
    "title": "The Godfather",
    "image": "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/rPdtLWNsZmAtoZl9PK7S2wE3qiS.jpg",
    "year": "1972",
    "genre": "Crime, Drama",
    "rating": "9.2",
    "description": "An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son.",
    "director": "Francis Ford Coppola",
    "cast": ["Marlon Brando", "Al Pacino", "James Caan"],
    "price": {
      "HD (2160p)": 12.99,
      "HD (1080p)": 9.99,
      "SD (720p)": 8.99,
      "SD (480p)": 7.99,
      "SD (240p)": 5.99,
    },
    "languages": ["English", "Spanish", "Tamil"],
  },
  {
    "id": 3,
    "title": "The Dark Knight",
    "image": "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg",
    "year": "2008",
    "genre": "Action, Crime, Drama",
    "rating": "9.0",
    "description": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    "director": "Christopher Nolan",
    "cast": ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    "price": {
      "HD (2160p)": 12.99,
      "HD (1080p)": 9.99,
      "SD (720p)": 8.99,
      "SD (480p)": 7.99,
      "SD (240p)": 5.99,
    },
    "languages": ["English", "Spanish", "Tamil"],
  }
]

export default movies;